version: '2'
services:
  db:
    image: postgres
    volumes:
      - adhoc-db-volume:/var/lib/postgresql/data  
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/adhoc
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db 
volumes:
  adhoc-db-volume:
    external: true