default: &default
 encoding: unicode
 adapter: postgresql
 username: postgres
 password: postgres
 host: localhost
 pool: 5

development:
 <<: *default
 database: adhoc_development

test:
 <<: *default
 database: adhoc_test
