require_relative '../spec/fabrica_de_objetos'

fabrica_de_objetos = FabricaDeObjetos.new

abogado_hommbre = fabrica_de_objetos.un_abogado
abogada_mujer = fabrica_de_objetos.otro_abogado

cliente_hommbre = fabrica_de_objetos.crear_cliente(abogado_hommbre.id)
cliente_mujer = fabrica_de_objetos.crear_otro_cliente(abogada_mujer.id)

expediente_hombre = fabrica_de_objetos.un_expediente_para(cliente_hommbre.id)
expediente_mujer = fabrica_de_objetos.un_expediente_para(cliente_mujer.id)

expediente_archivado_hombre = fabrica_de_objetos.un_expediente_archivado_para(cliente_mujer.id)
expediente_archivado_mujer = fabrica_de_objetos.un_expediente_archivado_para(cliente_mujer.id)

fabrica_de_objetos.una_demanda_para(expediente_hombre.id)
fabrica_de_objetos.una_contestacion_de_demanda_para(expediente_hombre.id)
fabrica_de_objetos.un_mero_tramite_para(expediente_hombre.id)

fabrica_de_objetos.una_demanda_para(expediente_archivado_hombre.id)
fabrica_de_objetos.una_contestacion_de_demanda_para(expediente_archivado_hombre.id)
fabrica_de_objetos.un_mero_tramite_para(expediente_archivado_hombre.id)

fabrica_de_objetos.una_demanda_para(expediente_mujer.id)
fabrica_de_objetos.una_contestacion_de_demanda_para(expediente_mujer.id)
fabrica_de_objetos.un_mero_tramite_para(expediente_mujer.id)

fabrica_de_objetos.una_demanda_para(expediente_archivado_mujer.id)
fabrica_de_objetos.una_contestacion_de_demanda_para(expediente_archivado_mujer.id)
fabrica_de_objetos.un_mero_tramite_para(expediente_archivado_mujer.id)

fabrica_de_objetos.un_adjunto(expediente_hombre)
fabrica_de_objetos.otro_adjunto(expediente_mujer)
